# Generated by Django 4.0.6 on 2023-01-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('year_of_birth', models.IntegerField(blank=True, default=1970, null=True)),
            ],
        ),
    ]
